src/Entity/Tags.php
<?php

namespace App\Entity;

use App\Repository\TagsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TagsRepository::class)
 */
class Tags
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tag_name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToMany(targetEntity=Products::class, inversedBy="tags")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTagName(): ?string
    {
        return $this->tag_name;
    }

    public function setTagName(string $tag_name): self
    {
        $this->tag_name = $tag_name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|Products[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Products $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
        }

        return $this;
    }

    public function removeProduct(Products $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
        }

        return $this;
    }
}

src/Controller/Cms/CategoriesController.php
<?php

namespace App\Controller\Cms;

use App\Service\Cms\CategoriesService;

use App\Validation\ValidatedRequest;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
// /**
//     * Require ROLE_ADMIN for *every* controller method in this class.
//     *
//     * @IsGranted("ROLE_ADMIN")
// */

class CategoriesController extends AbstractController
{
    /**
        * Require ROLE_ADMIN for only this controller method.
        *
        * @IsGranted("ROLE_ADMIN")
    */

    private $categories;

    public function __construct(CategoriesService $categories){
        $this->categories = $categories;
    }


    /**
     * @Route("cms/categories/list-categories", name="listCategories")
     */
    public function index()
    {
        $categories = $this->categories->getAll();

        return $this->render('cms/categories/listCategories.html.twig', [
            'categories' => $categories
        ]);
    }



    /**
     * @Route("cms/categories/create-categories", name="showCreateCategories")
     */
    public function showCreate()
    {
        return $this->render('cms/categories/createCategories.html.twig');
    }
   
    /**
     * @Route("cms/categories/createAction", name="createCategories")
     */
    public function createCategories(Request $request)
    {
        $data = $request->request->all(); //lấy dl từ form bỏ vào object data.

        if (!ValidatedRequest::isValidatedname($data)) {
            return $this->json($this->notificationFailed());
        }

        $result = $this->categories->createCate($data); // đưa dl đến services để xli

        return $this->json($result);
    }





    /**
     * @Route("cms/categories/edit-Categories/{id}", name="showEditCategories", methods={"GET"})
     */
    public function showEdit(int $id)
    {
        $catagoriesById = $this->categories->get($id);

        return $this->render('cms/categories/editCategories.html.twig', [
            'categoriesById' => $catagoriesById
        ]);
    }

    /**
     * @Route("cmscategories/editAction", name="editCategories")
     */
    public function editCategories(Request $request)
    {
        $data = $request->request->all();

        if (!ValidatedRequest::isValidatedName($data)) {
            return $this->json($this->notificationFailed());
        }

        $result = $this->categories->editCate($data);

        return $this->json($result);
    }




    /**
     * @Route("cms/categories/remove-categories/{id}", name="removeCategories", methods={"GET"})
     */
    public function removeCategories(int $id)
    {   
        $this->categories->removeCategories($id);

        return $this->redirectToRoute('listCategories');
    }



    // notification failed:
    private function notificationFailed()
    {
        return [
            'status' => 'failed',
            'message' => 'failed at validated',
            'error' => 'error'
        ];
    }

}

src/Controller/Cms/CommentController.php
<?php

namespace App\Controller\Cms;


use App\Service\Cms\ComnentService;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\HttpFoundation\Request;

class CommentController extends AbstractController
{
    private $comnentService;
    // private $comments;
    public function __construct(ComnentService $comnentService)
    {
        $this->comnentService = $comnentService;
    }
    /**
     * @Route("/comment", name="comment")
     */
    public function index(Request $request)
    {
        $data = $request->request->all(); // lấy dl từ request đưa vào $data
        
        $this->comnentService->create($data); //đưa dữ liệu đến service


        return $this->render('cms/comment/index.html.twig', [
            'controller_name' => 'abc'
        ]);
    }
}

src/Controller/Cms/DemoController.php
<?php

namespace App\Controller\Cms;

use App\Service\NewsService;
// use Symfony\Component\BrowserKit\Response;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DemoController extends AbstractController
{
    private $service1;

    public function __construct()
    {
        
    }

    /**
     * @Route("/demo", name="demo")
     */
    public function index()
    {
        // $news = $this->service1->getNews();
        $view = $this->renderView('cms/demo/index.html.twig', [
            'controller_name' => 'demo',
            'messages' => ['tét', 'fgfg']
        ]);

        return new Response($view);
    }

    /**
     * @Route("/dashboard", name="dashboard")
     */
    public function dashboard()
    {
        return $this->renderView('cms/dasdboard/index.html.twig');
    }
}

src/Controller/Cms/ProductsController.php
<?php

namespace App\Controller\Cms;

// validated
use App\Validation\ValidatedRequest;
use App\Validation\ValidatedUpload;

// ho tro duong dan theo invỉoment
use App\Helper\UploadHelper;

use App\Service\Cms\ProductsService;
use App\Service\Cms\CategoriesService;
use App\Service\Cms\TagsService;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

use Symfony\Component\HttpFoundation\File\UploadedFile;

class ProductsController extends AbstractController
{
    
    private $products;
    private $categories;
    private $tags;

    public function __construct(
        ProductsService $products,
        CategoriesService $catagories,
        TagsService $tagsService
    ) {
        $this->products = $products;
        $this->categories = $catagories;
        $this->tags = $tagsService;
    }

    /**
     * @Route("cms/products/list-products", name="listProducts")
     */
    public function index()
    {   
        // check admin:
        
        $products = $this->products->getAll();

        return $this->render('cms/products/listProducts.html.twig', [
            'products' => $products,
        ]);
    }



    /**
     * @Route("cms/products/create-products", name="Products")
     */
    // dung de tao router toi trang create product
    public function showCreate()
    {
        $categories = $this->categories->getAll();
        $tags = $this->tags->getAll();
        
        return $this->render('cms/products/createProducts.html.twig', [
            'categories' => $categories,
            'tags' => $tags
        ]);
    }

    /**
     * @Route("cms/createActions", name="createProducts")
     */
    public function createProducts(Request $request)
    {
        $files = $request->files->all();
        $imageFile = $files['images'];
        $data = $request->request->all();

        if (!ValidatedRequest::isValidatedName($data) ||
            !ValidatedRequest::isValidatedPrice($data) || 
            !ValidatedRequest::isValidatedCheckbox($data) ||

            !ValidatedUpload::validateImageCreate($imageFile))
        {
            return $this->json($this->notificationFailed());
        }

        $data['image_name'] = ValidatedUpload::uploadImage($imageFile);

        $result = $this->products->createPro($data);

        return $this->json($result);
    }




    /**
     * @Route("cms/products/edit-products/{id}", name="showEdit", methods={"GET"})
     */
    // dung de tao router toi trang create product
    public function showEdit(int $id)
    {
        $conditions = ['id' => $id];

        $products = $this->products->getOneBy($conditions);
        $idTagsOfProduct = $this->products->getTagsOfProducts($products);
        $categories = $this->categories->getAll();
        
        $tags = $this->tags->getAll();
        
        return $this->render('cms/products/editProducts.html.twig', [
            'products' => $products,
            'idTagsOfProduct' => $idTagsOfProduct,
            'categories' => $categories,
            'tags' => $tags
        ]);
    }
    /**
     * @Route("cms/edit-products", name="editProducts")
     */
    public function editProducts(Request $request)
    {
        $data = $request->request->all();
        $files = $request->files->all();

        $imageFile = $files['images'];
        $product_image_text  = $data['product_image_text'];

        if (!ValidatedRequest::isValidatedName($data) ||
            !ValidatedRequest::isValidatedPrice($data) || 
            !ValidatedRequest::isValidatedCheckbox($data)
            ) {

            return $this->json($this->notificationFailed());
        }

        if (!empty($imageFile)) {
            if (ValidatedUpload::validateImageEdit($imageFile)) {
                $data['image_name'] = ValidatedUpload::uploadImage($imageFile);
            }
            else {
                return $this->json([
                    'status' => 'failed',
                    'message' => 'failed uppload file at edit',
                    'error' => 'no error'
                ]);
            }
        }
        else {
            $data['image_name'] = $product_image_text;
        }

        $result = $this->products->editPro($data);

        return $this->json($result);
    }





    /**
     * @Route("cms/removeAction", name="removeProducts")
     */
    public function removeProducts(Request $request)
    {
        $data = $request->request->all();
        $id_product = $data['id_product'];

        $result = $this->products->removePro($id_product);

        return $this->redirectToRoute('listProducts', $result);
    }



    /**
     * @Route("cms/search-products", name="searchProducts")
     */
    public function searchProducts(Request $request)
    {
        $data = $request->request->all();

        // $searchOption = $data['searchOption'];

        $result = $this->products->searchPro($data);

        $html = $this->renderView('cms/products/product_rows.html.twig', [
            'products' => $result,
            'product_upload_image_folder' => $_ENV['BASE_UPLOAD_FOLDER'] . '/' . $_ENV['PRODUCT_UPLOAD_FOLDER'] . '/' . $_ENV['PRODUCT_IMAGE_FOLDER'],
        ]);

        return $this->json([
            'status' => 'success',
            'html' => $html,
        ]);
    }



    // notification failed:
    private function notificationFailed()
    {
        return [
            'status' => 'failed',
            'message' => 'failed at validate',
            'error' => 'error'
        ];
    }
}

src/Controller/Cms/TagsController.php
<?php

namespace App\Controller\Cms;

use App\Service\Cms\TagsService;

use App\Validation\ValidatedRequest;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class TagsController extends AbstractController
{
    private $tags;

    public function __construct(TagsService $tagsService){
        $this->tags = $tagsService;
    }

    /**
     * @Route("cms/tags/list-tags", name="listTags")
     */
    public function index()
    {
        $result = $this->tags->getAll();

        return $this->render('cms/tags/listTags.html.twig', [
            'tags' => $result,
        ]);
    }

    /**
     * @Route("cms/tags/create-tags", name="showCreateTags")
     */
    public function showCreate()
    {
        return $this->render('cms/tags/createTags.html.twig');
    }
   
    /**
     * @Route("cms/tags/createAction", name="createTags")
     */
    public function createTags(Request $request)
    {
        $data = $request->request->all(); //lấy dl từ form bỏ vào object data.

        if (!ValidatedRequest::isValidatedname($data)) {
            return $this->json($this->notificationFailed());
        }

        $result = $this->tags->createTags($data);

        return $this->json($result);
    }



    /**
     * @Route("cms/tags/edit-tags/{id}", name="showEditTags", methods={"GET"})
     */
    public function showedit(int $id)
    {
        $result = $this->tags->getById($id);
        //dd($result);
        return $this->render('cms/tags/editTags.html.twig', [
            'tagById' => $result,
        ]);
    }
    /**
     * @Route("cms/tags/editAction", name="editTags")
     */
    public function editTags(Request $request)
    {
        $data = $request->request->all(); //lấy dl từ form bỏ vào object data.

        $result = $this->tags->editTag($data);

        return $this->json($result);
    }


    /**
     * @Route("cms/tags/removeAction", name="removeTags", methods={"POST"})
     */
    public function removeTag(Request $request)
    {
        $data = $request->request->all();

        $result = $this->tags->removeTag($data);

        return $this->json($result);
    }

    // notification failed:
    private function notificationFailed()
    {
        return [
            'status' => 'failed',
            'message' => 'failed at validated',
            'error' => 'error'
        ];
    }


}

templates/cms/tags/createTags.html.twig
{% extends "cms/base.html.twig" %}

{% block title %}Create Tags{% endblock %}

{% block main_content %}
    <!-- Main content -->
    <section class="content-header">
      <h1>
        Data Tables
        <small>advanced tables</small>
      </h1>
    </section>
        <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                <h3 class="box-title">create Tags</h3>
                </div>
                <!-- /.box-header ===============================================================-->
                <!-- form start -->
                <form id="formSubmited" role="form" method="POST" action="{{ path('createTags') }}">
                <div class="box-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Name Tag</label>
                    <input name="name" type="text" class="form-control" id="input-name" placeholder="Enter tags">
                    </div>
                    <div class="form-group">
                    <div class="checkbox">
                    <label>
                        <input type="checkbox"> Check me out
                    </label>
                    </div>
                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                </form>
            </div>
            <!-- /.box =================================================================-->
            </div>
            <!--/.col (left) -->
            <!-- right column -->
            
        </div>
        <!-- /.row -->
        </section>
        <!-- /.content -->
{% endblock %}

templates/cms/tags/editTags.html.twig
{% extends "cms/base.html.twig" %}

{% block title %}Edit Tags{% endblock %}

{% block main_content %}
<!-- Main content -->
<section class="content-header">
    <h1>
        Data Tables
        <small>advanced tables</small>
    </h1>
</section>
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit Tags</h3>
                </div>
                <!-- /.box-header ===============================================================-->
                <!-- form start -->
                <form id="formSubmited" role="form" method="POST" action="{{ path('editTags') }}"
                    enctype="multipart/form-data">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Name Tags</label>
                            <input name="id_tag" type="hidden" class="form-control" id="input-name"
                                value="{{ tagById.id }}">
                            <input name="name" type="text" class="form-control" id="input-name"
                                value="{{ tagById.tagName }}">
                        </div>

                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> Check me out
                            </label>
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
            </div>
            </form>
        </div>
        <!-- /.box =================================================================-->
    </div>
    <!--/.col (left) -->
    <!-- right column -->

    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
{% endblock %}

templates/cms/tags/listTags.html.twig
{% extends "cms/base.html.twig" %}

{% block title %}list Tags{% endblock %}

{% block main_content %}
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">list Tags</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>name</th>
                <th>created</th>
                <th>updated</th>
                <th>edit</th>
                <th>remove</th>
              </tr>
            </thead>

            <tbody>
              {% for tag in tags %}
              <tr>
                <td>{{ tag.tagName }}</td>
                <td>
                  {{ tag.createdAt|date("m/d/Y") }}
                </td>
                <td>
                  {{ tag.updatedAt|date("m/d/Y") }}
                </td>

                <td>
                  <a href="{{ path('showEditTags', { id: tag.id }) }}">Edit</a>
                </td>

                <td>
                  <a class="removeClicked" href="javascript:void(0);" data-id="{{ tag.id }}" />Remove</a>
                </td>

              </tr>

              {% endfor %}

            </tbody>

            <tfoot>
              <tr>
                <th>name</th>>
                <th>created</th>
                <th>updated</th>
                <th>edit</th>
                <th>remove</th>
              </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
  </div>
</section>
{% endblock %}